### ISSUE TITLE
Kafka Listener listening on wrong port

### ISSUE THREAD

**Issue by OliverW21** [The-Microservice-Dungeon/generic-player#28]
The Kafkalistener listens on `kafka:9092` regardless of what is configured in the .env file. 

The intended env value gets passed correctly to application.yaml and to the code.

Even the log at the start prints out the correct config.
```
2022-01-05 21:22:26.345  INFO 3404 --- [  restartedMain] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [localhost:29092]
        ....
```
Removing the `spring.kafka.bootstrap.servers` key from application.yaml causes kafka to try to connect to `localhost/127.0.0.1:9092` and the config log at the start also prints this as the value for bootstrap.servers.
```
2022-01-05 21:25:27.784  INFO 20984 --- [  restartedMain] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [localhost:9092]
```
This does not seem to be a configuration issue, rather that kafka reads the value from somewhere else if its set. `kafka:9092` is nowhere to be found in the source except in .env.docker, but changing it in there does not affect the broken behaviour of the listener.

Maybe helpful reference: https://stackoverflow.com/a/51638268 (I've checked but could not find any @Configuration Beans that where overwriting these options. But I am not very familiar with this topic)

**Comment by stefanbente** [comment]
see https://github.com/The-Microservice-Dungeon/local-dev-environment/issues/4
